export enum UserInputLength{
    MIN_USERNAME_LENGTH = 5,
    MAX_USERNAME_LENGTH = 25,
    MAX_PASSWORD_LENGTH = 200,
    MIN_PASSWORD_LENGTH = 5,
    MAX_EMAIL_LENGTH = 35,
    MIN_EMAIL_LENGTH = 10,
    MIN_PHONE_LENGTH = 6,
    MAX_PHONE_LENGTH = 13,
    MIN_ACADEMIC_LEVEL_LENGTH = 6,
    MAX_ACADEMIC_LEVEL_LENGTH = 100,
    MIN_BUSINESS_CATEGORY_LENGTH = 6,
    MAX_BUSINESS_CATEGORY_LENGTH = 100,
    MIN_DEVEOPEMENT_FIELD_LENGTH = 6,
    MAX_DEVELOPMENT_FIELD_LENGTH = 100
}